replicas: 1
defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=10s
  - --kubelet-insecure-tls
  - --authorization-always-allow-paths=/metrics
metrics:
  enabled: true
serviceMonitor:
  enabled: false